import hobby from './hobby.svg'
import home from './home.svg'
import logo from './logo.png'
import mypage from './mypage.png'
import profile from './profile.png'
import study from './study.svg'
import mydesk from './mydesk.svg'
import unchecked from './unchecked.png'
import XIcon from './Vector.svg'
import colorChecked from './colorChecked.svg'
import addroom from './addroom.svg'
import kakao from './kakao.svg'
import google from './google.svg'

export { kakao, google, addroom, colorChecked, XIcon, hobby, home, logo, study, mypage, profile, mydesk, unchecked}